In [1]:
import numpy
import numpy as np
from numpy import*

In [3]:
list=[1,2,3]

In [5]:
type(list)

list

In [6]:
arr=np.array(list)

In [7]:
arr

array([1, 2, 3])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.shape

(3,)

In [10]:
arr.ndim

1

In [12]:
arr2=np.array([1,2,3,4,5,6])

In [13]:
arr2


array([1, 2, 3, 4, 5, 6])

In [14]:
arr2[2:4]

array([3, 4])

In [17]:
arr2[4]=90

IndexError: list assignment index out of range

## 

In [18]:
arr2

[4]

In [19]:
list1 = [[1,2,3],[1,3,4],[8,9,0]]

In [20]:
listarr=np.array(list1)

In [21]:
listarr

array([[1, 2, 3],
       [1, 3, 4],
       [8, 9, 0]])

In [22]:
listarr.shape

(3, 3)

In [25]:
listarr.ndim

2

In [26]:
import pandas as pd

In [27]:
marks = [80,90,100,40]
labels = ["maths","science","physics","chem"]

In [28]:
ser = pd.Series(marks,labels)

In [29]:
ser

maths       80
science     90
physics    100
chem        40
dtype: int64

In [30]:
ser = pd.Series(data = marks,index = labels)

In [31]:
ser

maths       80
science     90
physics    100
chem        40
dtype: int64

In [32]:
type(ser)

pandas.core.series.Series

In [33]:
ser["maths"]

80

In [34]:
import numpy as np

In [35]:
p = np.arange(16).reshape(4,4)
labels = ['a','b','c','d']
label2 = ['A','B','C','D']

In [36]:
p

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
df = pd.DataFrame(p,index = labels,columns = label2)

In [38]:
df

A   B   C   D
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15

In [39]:
df1 = pd.DataFrame([[1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15,]], index = "A B C D".split(),columns = "a b c d".split())

"A B C D".split()

['A', 'B', 'C', 'D']

In [40]:
df1

a   b   c   d
A   1   2   3   4
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15

In [42]:
df1[['b','d']]

b   d
A   2   4
B   5   7
C   9  11
D  13  15

In [43]:
df1['new'] =df1['a']+df1['b']

In [44]:
df1

a   b   c   d  new
A   1   2   3   4    3
B   4   5   6   7    9
C   8   9  10  11   17
D  12  13  14  15   25

In [45]:
df1['new2'] = [1,2,4,6]

In [46]:
df1

a   b   c   d  new  new2
A   1   2   3   4    3     1
B   4   5   6   7    9     2
C   8   9  10  11   17     4
D  12  13  14  15   25     6

In [47]:
df1['a'].unique()


array([ 1,  4,  8, 12], dtype=int64)

In [48]:
df1['a'].value_counts()

8     1
1     1
4     1
12    1
Name: a, dtype: int64

In [49]:
df1.describe()

a          b          c          d        new      new2
count   4.000000   4.000000   4.000000   4.000000   4.000000  4.000000
mean    6.250000   7.250000   8.250000   9.250000  13.500000  3.250000
std     4.787136   4.787136   4.787136   4.787136   9.574271  2.217356
min     1.000000   2.000000   3.000000   4.000000   3.000000  1.000000
25%     3.250000   4.250000   5.250000   6.250000   7.500000  1.750000
50%     6.000000   7.000000   8.000000   9.000000  13.000000  3.000000
75%     9.000000  10.000000  11.000000  12.000000  19.000000  4.500000
max    12.000000  13.000000  14.000000  15.000000  25.000000  6.000000

In [50]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, A to D
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       4 non-null      int64
 1   b       4 non-null      int64
 2   c       4 non-null      int64
 3   d       4 non-null      int64
 4   new     4 non-null      int64
 5   new2    4 non-null      int64
dtypes: int64(6)
memory usage: 224.0+ bytes


In [51]:
df = pd.DataFrame({'A':[1,2,np.NaN],
                  'B':[5,np.NaN,np.NaN],
                  'C':[1,2,3]})

In [52]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [53]:
df = pd.DataFrame({'A':[1,2,np.NaN],
                  'B':[5,np.NaN,np.NaN],
                  'C':[1,2,3]})

In [54]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [55]:
df1 = pd.DataFrame(["Aindia" , np.nan, "Aindia","Australia","Australia","us","canada"],columns = ['country'])

df1

country
0     Aindia
1        NaN
2     Aindia
3  Australia
4  Australia
5         us
6     canada

In [56]:
dataset = pd.read_csv(r"D:\pythonbasics\50_Startups.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\pythonbasics\\50_Startups.csv'

In [57]:
data = pd.DataFrame({'1':  ['h', 'e','l','l','o',np.NaN,'n','a','i','t'],
        '2':  ['h', 'e','l','l','o','n','a','i',np.NaN,'t'],
        '3':  ['h', 'e','l','l','o',np.NaN,'n','a','i','t'],
        '4':  ['h', 'e','l','l','o',np.NaN,'n','a','i','t'],
        '5':  ['h', 'e',np.NaN,'l','o','n','a','i','t','k'],
        '6':  ['h',np.NaN,'l','l','o','k','n','a','i','t'],
        '7':  ['h', 'e','l','l','o',np.NaN,'n','a','i','t']})
data

1    2    3    4    5    6    7
0    h    h    h    h    h    h    h
1    e    e    e    e    e  NaN    e
2    l    l    l    l  NaN    l    l
3    l    l    l    l    l    l    l
4    o    o    o    o    o    o    o
5  NaN    n  NaN  NaN    n    k  NaN
6    n    a    n    n    a    n    n
7    a    i    a    a    i    a    a
8    i  NaN    i    i    t    i    i
9    t    t    t    t    k    t    t

In [58]:
pdataset = pd.read_excel("datasetexcel.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'datasetexcel.xlsx'

In [3]:
from flask import Flask, request, render_template

In [4]:
import numpy as np

In [5]:
import re

In [6]:
import requests

In [7]:
app=Flask(__name__)

In [9]:
import requests

url = "https://zyanyatech1-license-plate-recognition-v1.p.rapidapi.com/recognize_url"

querystring = {"image_url":"http://eslamoda.com/wp-content/uploads/sites/2/2014/11/america-carro-600x600.jpg"}

headers = {
    'x-rapidapi-key': "d9a2b6475emsh890c2568688f89fp1d481ajsn28c7cb4f8a78",
    'x-rapidapi-host': "zyanyatech1-license-plate-recognition-v1.p.rapidapi.com"
    }

response = requests.request("POST", url, headers=headers, params=querystring)

print(response.text)
return response.json()["results"][0]["plate"], response.json()["results"][0]["confidence"]

{"uuid":"","data_type":"alpr_results","epoch_time":1622378248980,"processing_time":{"plates":42.48637772,"total":48.77699999997276},"img_height":600,"img_width":600,"results":[{"plate":"MHJ3719","confidence":93.81554413,"region_confidence":92,"vehicle_region":{"y":63,"x":48,"height":516,"width":525},"region":"mx-mex","plate_index":0,"processing_time_ms":11.49129295,"candidates":[{"matches_template":0,"plate":"MHJ3719","confidence":93.81554413}],"coordinates":[{"y":487,"x":255},{"y":489,"x":374},{"y":541,"x":370},{"y":538,"x":252}],"matches_template":0,"requested_topn":10}],"version":2,"error":false,"regions_of_interest":[{"y":0,"x":0,"height":600,"width":600}]}


SyntaxError: 'return' outside function (<ipython-input-9-af8580672d40>, line 15)

In [11]:
@app.route('/')
def home():
    return render_template('base.html')

AssertionError: View function mapping is overwriting an existing endpoint function: home